#!/bin/bash

export EDITOR='vim -f'
export HISTCONTROL=ignoredups
export HISTIGNORE="&:ls:[bf]g:exit"
export HISTSIZE=100000
export PROMPT_COMMAND='echo -ne "\033]0; ${PWD##*/}\007"'

shopt -s cdspell
shopt -s cmdhist
shopt -s histappend

# Tab complete in sudo
complete -cf sudo

# Aliases
alias vi='vim'
alias ls="ls -lh -GFp"
alias sl='ls'
alias diff='diff -u'

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.config/dircolors && eval "$(dircolors -b ~/.config/dircolors)" || eval "$(dircolors -b)"
  alias ls='ls -alh -GFp --color=auto'
  alias grep='grep --color=auto'
fi

# Print current banch
function git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo ${ref#refs/heads/}
}

# Colors
color_off='\e[0m' # Text Reset
black='\e[0;30m' # Black
red='\e[0;31m' # Red
orange='\e[1;31m' # Orange
green='\e[0;32m' # Green
yellow='\e[0;33m' # Yellow
blue='\e[0;34m' # Blue
purple='\e[0;35m' # Purple
cyan='\e[0;36m' # Cyan
white='\e[0;37m' # White
PS1="\[${green}\]\u\[${white}\]@\[${blue}\]\h \[${yellow}\]\w\[${orange}\] \$(git_branch) \n\[${green}\]$ \[${color_off}\]"

# Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# Language configs
[ -e ~/.lang/python ] && source ~/.lang/python
[ -e ~/.lang/ruby ] && source ~/.lang/ruby

# Work configs
[ -e ~/.workrc ] && source ~/.workrc
