#!/bin/bash

export EDITOR='vim -f'
export HISTCONTROL=ignoredups
export HISTIGNORE="&:ls:[bf]g:exit"
export HISTSIZE=100000

shopt -s cdspell
shopt -s cmdhist
shopt -s histappend

# Tab complete in sudo
complete -cf sudo

# Aliases
alias vi='vim'
alias ls="ls -GFp"
alias sl='ls'

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.config/dircolors && eval "$(dircolors -b ~/.config/dircolors)" || eval "$(dircolors -b)"
  alias ls='ls -GFp --color=auto'
  alias grep='grep --color=auto'
fi

# Print current banch
function git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo ${ref#refs/heads/}
}

# Colors
color_off='\e[0m' # Text Reset
black='\e[0;30m' # Black
red='\e[0;31m' # Red
orange='\e[1;31m' # Orange
green='\e[0;32m' # Green
yellow='\e[0;33m' # Yellow
blue='\e[0;34m' # Blue
purple='\e[0;35m' # Purple
cyan='\e[0;36m' # Cyan
white='\e[0;37m' # White
PS1="\[${green}\]\u\[${white}\]@\[${blue}\]\h \[${yellow}\]\w\[${orange}\] \$(git_branch) \n\[${green}\]$ \[${color_off}\]"

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# virtualenv
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Development
# for OSX/homebrew
if [ -e /usr/local/bin/python ]; then
  export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
fi
[ -e /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh

# Git branch completion
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# Work configs
[ -e ~/.workrc ] && source ~/.workrc
