""
"" Settings reference: https://github.com/carlhuda/janus
""

""
"" Basic setup
""

set nocompatible    " Use vim, no vi defaults

set cursorline      " Show cursor line
set number          " Show line numbers
set ruler           " Show line and column number
set wildmenu        " Enhanced command-line completion

set encoding=utf-8  " Set default encoding to UTF-8

set fillchars=""    " Remove characters in window splits
set laststatus=2    " Always show statusline
set noshowmode      " Hide mode from statusline
set novisualbell    " Disable visual bell
set scrolloff=5     " Number of lines of context when scrolling
set showmatch       " Show matching brackets
set splitbelow      " Horizontal split below
set splitright      " Vertical split to the right

""
"" Pathogen
""

runtime bundle/plugin-pathogen/autoload/pathogen.vim
filetype off
let g:pathogen_disabled = ['pathogen']
call pathogen#incubate()
call pathogen#helptags()

""
"" Whitespace
""

set nowrap                      " Don't wrap lines visually
set textwidth=79                " Wrap lines physically at 79

set tabstop=2                   " Tab is two spaces
set shiftwidth=2                " Autoindent is two spaces
set expandtab                   " Use spaces, not tabs

set backspace=indent,eol,start  " Allow backspace to remove these characters

set list                      " Show invisible characters
set listchars=""              " Reset the listchars
set listchars=tab:\ \         " A tab should display as "  ", trailing whitespace as "."
set listchars+=trail:.        " Show trailing spaces as dots
set listchars+=extends:>      " The character to show in the last column when wrap is
                              " off and the line continues beyond the right of the screen
set listchars+=precedes:<     " The character to show in the last column when wrap is
                              " off and the line continues beyond the left of the screen

""
"" Keyboard mappings
""

" Map leader key
let mapleader = ","

" Switch buffers
map <Tab> :bnext<CR>
map <S-Tab> :bprevious<CR>

" Resize windows
nnoremap <silent> + :exe "resize " . (winheight(0) * 3/2)<CR>
nnoremap <silent> - :exe "resize " . (winheight(0) * 2/3)<CR>

" Window movement
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Clear highlighting
nnoremap <F3> :set hlsearch!<CR>

" Open new tab
nnoremap <silent> <C-W>t :tabnew<CR>

" Disable arrow keys (force good habits)
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
vnoremap <up> <nop>
vnoremap <down> <nop>
vnoremap <left> <nop>
vnoremap <right> <nop>

" Map plugin panes
map <Leader>m :TagbarToggle<CR>
map <Leader>t <plug>NERDTreeTabsToggle<CR>

""
"" Searching
""

set hlsearch    " Highlight matches
set incsearch   " Incremental searching
set ignorecase  " Ignore case when searching
set smartcase   " Don't ignore case if contains at least one capital letter

""
"" File-specific
""

filetype indent plugin on   " Enable filetype plugins

au BufNewFile,BufRead *.djhtml set filetype=html
au BufNewFile,BufRead *.json set filetype=javascript
au BufNewFile,BufRead *.yaml,*.yml so ~/.vim/bundle/lang-yaml/colors/yaml.vim

au FileType make setlocal noexpandtab
au FileType python setlocal softtabstop=4 tabstop=4 shiftwidth=4

""
"" Color & syntax
""

syntax enable               " Enable syntax highlighting
set background=light        " Set background color
colorscheme solarized       " Set colorscheme

set cc=80                   " Color specific column
set t_Co=256                " Enable 256 colors support
highlight clear SignColumn  " Color fix for gitgutter and solarized

""
"" Miscellaneous
""

" Fix for lag when exiting insert mode
if ! has('gui_running')
    set ttimeoutlen=10
    augroup FastEscape
        autocmd!
        au InsertEnter * set timeoutlen=0
        au InsertLeave * set timeoutlen=1000
    augroup END
endif

""
"" Plugin-specific
""

" Syntastic settings
let g:syntastic_auto_loc_list=1   " Automatically open error list
let g:syntastic_mode_map = { 'mode': 'active',
                           \ 'active_filetypes': [],
                           \ 'passive_filetypes': ['python'] }
let g:syntastic_python_checkers=['pylint']

" SuperTab: determine which completion mode to use
let g:SuperTabDefaultCompletionType = "context"

" Airline settings
let g:airline_enable_fugitive=1
let g:airline_enable_syntastic=1
let g:airline_powerline_fonts = 1
let g:airline_theme='solarized'
let g:airline#extensions#tabline#enabled = 1

" Jedi settings
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0
let g:jedi#show_call_signatures = 0
let g:jedi#use_splits_not_buffers = "left"
